### ISSUE TITLE
页面销毁后还会继续倒计时吗

### ISSUE THREAD

**Issue by ljackChen001** [thepacific/timer#3]
倒计时途中，销毁页面，重新进入页面，倒计时还未结束，倒计时还会一直倒下去吗

**Comment by hwt88** [comment]
@ljackChen001 如果timer是在该页面创建的，那么页面退出，没有stop掉，会计时下去，但会导致内存泄漏，你再次进入页面的时候，这个timer已经不是之前的那个timer了。所以要满足继续计时的需求，请将timer创建在不依赖于界面的地方。当进入界面获取当前计时值即可。

**Comment by zhang-kuo** [comment]
为什莫不是jar文件啊

**Comment by hwt88** [comment]
@zhangkuo123 个人觉得没必要。如果你有特殊需求，自行拷贝源码，只有一个类而已。
